Dockerfile: Pin the setuptools version to 45.1.0
This updates the python setuptools package to be a version that does not require Python 3.5+ support. We inherit the python version from the ocp-operator-sdk repository, which made the switch to Python3 sometime in the release-4.4 cycle.

The following error was popping up in the failed image build:
```
Requirement already satisfied, skipping upgrade: setuptool...site-packages (from kubernetes~=11.0.0->openshift) (45.2.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.5 not in '>=3.5'
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.
error: build error: running 'pip install --no-cache-dir --upgrade openshift boto3 cryptography' failed with exit code 1
time="2020-06-30T14:10:23Z" level=info msg="Reporting job state \"failed\" with reason \"executing_graph:step_failed:building_project_image\""
```

If we instead pip the version of that package to the previous minor version (45.1.0), we can successfully build the metering-ansible-operator image again.