Dockerfile: Ensure the Ansible version is less than 2.10
This updates the CI and ART Dockerfiles to ensure the Ansible version we're pulling in from the ocp-ansible-operator base image is a version of Ansible we have tested against. Recently, it looks like the Ansible 2.10 version is now available in that base image, which produced the following build error message when attempting to pip install Ansible:

```log
STEP 16: RUN pip install --no-cache-dir --upgrade ansible~=2.9 openshift botocore boto3 cryptography netaddr
Collecting ansible~=2.9
  Downloading ansible-2.10.0.tar.gz (25.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u135l3lr/ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u135l3lr/ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u135l3lr/ansible/pip-egg-info
         cwd: /tmp/pip-install-u135l3lr/ansible/
    Complete output (31 lines):

                ### ERROR ###

                Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is
                known to cause problems.  Please uninstall the old version found at:

                /usr/local/lib/python3.6/site-packages/ansible/__init__.py

                and install the new version:

                    pip uninstall ansible
                    pip install ansible

                If you have a broken installation, perhaps because ansible-base was installed before
                ansible was upgraded, try this to resolve it:

                    pip install --force-reinstall ansible ansible-base

                If ansible is installed in a different location than you will be installing it now
                (for example, if the old version is installed by a system package manager to
                /usr/lib/python3.8/site-packages/ansible but you are installing the new version into
                ~/.local/lib/python3.8/site-packages/ansible with `pip install --user ansible`)
                or you want to install anyways and cleanup any breakage afterwards, then you may set
                the ANSIBLE_SKIP_CONFLICT_CHECK environment variable to ignore this check:

                    ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install --user ansible

                ### END ERROR ###
```

In order to avoid bumping the Ansible version to the most recent available in a 4.5 z-stream release, we can ensure that the Ansible version is at least 2.9, which we have tested, but set an upper bound to ensure the recently release 2.10 version does not get installed.