test/e2e: Wait for the s3 bucket to be deleted.
We've been seeing the following error in the e2e test logs recently:

```
        --- FAIL: TestManualMeteringInstall/S3-ReportDynamicInputData/testEnsureS3BucketIsDeleted (3.46s)
            delete_s3_bucket_test.go:44:
                	Error Trace:	delete_s3_bucket_test.go:44
                	            				metering_manual_install_tests.go:98
                	Error:      	Received unexpected error:
                	            	BucketNotEmpty: The bucket you tried to delete is not empty
                	            		status code: 409, request id: C8BBCA0B31687E41, host id: Ft4Tt7teHmz/Fxv2cP9IRs0RnCw5KNIKttizkx592BlsA9S9nqkVlhW0ryStlrvk1fzSlvBegf4=
                	Test:       	TestManualMeteringInstall/S3-ReportDynamicInputData/testEnsureS3BucketIsDeleted
                	Messages:   	failed to delete the metering-dev-e2e bucket
```

The call to batch delete all of the objects in a bucket happens in the background, so updating to use this client method where we wait until the bucket delete call is successful, or unless the maximum retries has been reached, is a step in the right direction.